export const CREATE_MEETUP = 'CREATE_MEETUP';
export const UPDATE_MEETUP = 'UPDATE_MEETUP';
export const DELETE_MEETUP = 'DELETE_MEETUP';
export const FIND_MEETUP_BY_TITLE = 'FIND_MEETUP_BY_TITLE';

export const GET_MEETUPS = 'GET_MEETUPS';
export const GET_NEXT_MEETUPS = 'GET_NEXT_MEETUPS';
export const GET_PAST_MEETUPS = 'GET_PAST_MEETUPS';
export const GET_MEMBERS = 'GET_MEMBERS';
export const GET_LIST_MEETUPS = 'GET_LIST_MEETUPS';
